### ISSUE TITLE
Leaked ServiceConnection

### ISSUE THREAD

**Issue by jochenberger** [noinnion/newsplus#75]
This is an excerpt from a recent logcat:

```
E/ActivityThread(22487): android.app.ServiceConnectionLeaked: Service com.noinnion.android.newsplus.reader.service.SyncService has leaked ServiceConnection com.noinnion.android.newsplus.extension.ExtensionHost$ClientConnection@64c110f0 that was originally bound here
E/ActivityThread(22487):        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:986)
E/ActivityThread(22487):        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:880)
E/ActivityThread(22487):        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1619)
E/ActivityThread(22487):        at android.app.ContextImpl.bindService(ContextImpl.java:1602)
E/ActivityThread(22487):        at android.content.ContextWrapper.bindService(ContextWrapper.java:517)
E/ActivityThread(22487):        at com.noinnion.android.newsplus.extension.ExtensionHost.execute(ExtensionHost.java:161)
E/ActivityThread(22487):        at com.noinnion.android.newsplus.reader.service.SyncService.startSync(SyncService.java:135)
E/ActivityThread(22487):        at com.noinnion.android.newsplus.reader.service.SyncService.handleIntent(SyncService.java:130)
E/ActivityThread(22487):        at com.noinnion.android.newsplus.reader.service.SyncService.onStartCommand(SyncService.java:109)
E/ActivityThread(22487):        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2722)
E/ActivityThread(22487):        at android.app.ActivityThread.access$2100(ActivityThread.java:145)
E/ActivityThread(22487):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
E/ActivityThread(22487):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/ActivityThread(22487):        at android.os.Looper.loop(Looper.java:136)
E/ActivityThread(22487):        at android.app.ActivityThread.main(ActivityThread.java:5144)
E/ActivityThread(22487):        at java.lang.reflect.Method.invoke(Native Method)
E/ActivityThread(22487):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
E/ActivityThread(22487):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
```

Looks as if a resource isn't closed properly.

**Comment by jochenberger** [comment]
Still there on 2.0.1
```
E/ActivityThread(10794): android.app.ServiceConnectionLeaked: Service com.noinnion.android.newsplus.reader.service.SyncService has leaked ServiceConnection com.noinnion.android.newsplus.extension.ExtensionHost$ClientConnection@41eca9e8 that was originally bound here
E/ActivityThread(10794):        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:977)
E/ActivityThread(10794):        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:871)
E/ActivityThread(10794):        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1625)
E/ActivityThread(10794):        at android.app.ContextImpl.bindService(ContextImpl.java:1608)
E/ActivityThread(10794):        at android.content.ContextWrapper.bindService(ContextWrapper.java:517)
E/ActivityThread(10794):        at com.noinnion.android.newsplus.extension.ExtensionHost.execute(ExtensionHost.java:161)
E/ActivityThread(10794):        at com.noinnion.android.newsplus.reader.service.SyncService.startSync(SyncService.java:127)
E/ActivityThread(10794):        at com.noinnion.android.newsplus.reader.service.SyncService.handleIntent(SyncService.java:122)
E/ActivityThread(10794):        at com.noinnion.android.newsplus.reader.service.SyncService.onStartCommand(SyncService.java:101)
E/ActivityThread(10794):        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2726)
E/ActivityThread(10794):        at android.app.ActivityThread.access$2100(ActivityThread.java:144)
E/ActivityThread(10794):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1302)
E/ActivityThread(10794):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/ActivityThread(10794):        at android.os.Looper.loop(Looper.java:136)
E/ActivityThread(10794):        at android.app.ActivityThread.main(ActivityThread.java:5146)
E/ActivityThread(10794):        at java.lang.reflect.Method.invokeNative(Native Method)
E/ActivityThread(10794):        at java.lang.reflect.Method.invoke(Method.java:515)
E/ActivityThread(10794):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
E/ActivityThread(10794):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
E/ActivityThread(10794):        at dalvik.system.NativeStart.main(Native Method)

```

**Comment by noinnion** [comment]
could you try the latest beta v2.0.2beta
http://noinnion.com/newsplus/updates/

**Comment by jochenberger** [comment]
Sorry, I don't install packages from untrusted sources. I'll report back if I have issues with the next stable release.

**Comment by jochenberger** [comment]
Still there in 2.0.2.
