### ISSUE TITLE
tt-rss plugin seems to "forget" authentication details

### ISSUE THREAD

**Issue by jochenberger** [noinnion/newsplus#80]
From time to time, refreshing a tt-rss subscription fails. When that happens, `ERROR_AUTHENTICATION: NOT_LOGGED_IN` is shown in a popup.
The logcat shows

```
W/System.err( 9421): com.noinnion.android.reader.api.ReaderException$ReaderLoginException: NOT_LOGGED_IN
W/System.err( 9421):    at com.noinnion.android.newsplus.extension.ttrss.TtRssExtension.handleError(TtRssExtension.java:369)
W/System.err( 9421):    at com.noinnion.android.newsplus.extension.ttrss.TtRssExtension.parseFeedList(TtRssExtension.java:610)
W/System.err( 9421):    at com.noinnion.android.newsplus.extension.ttrss.TtRssExtension.getFeedList(TtRssExtension.java:576)
W/System.err( 9421):    at com.noinnion.android.newsplus.extension.ttrss.TtRssExtension.handleReaderList(TtRssExtension.java:379)
W/System.err( 9421):    at com.noinnion.android.reader.api.ReaderExtension$1.handleReaderList(ReaderExtension.java:154)
W/System.err( 9421):    at com.noinnion.android.reader.api.internal.IReaderExtension$Stub.onTransact(IReaderExtension.java:71)
W/System.err( 9421):    at android.os.Binder.execTransact(Binder.java:404)
W/System.err(32501): com.noinnion.android.reader.api.ReaderException$ReaderLoginException: ERROR_AUTHENTICATION: NOT_LOGGED_IN
W/System.err(32501):    at com.noinnion.android.newsplus.reader.provider.ReaderManager.checkError(ReaderManager.java:1069)
W/System.err(32501):    at com.noinnion.android.newsplus.reader.provider.ReaderManager.syncReaderLists(ReaderManager.java:1710)
W/System.err(32501):    at com.noinnion.android.newsplus.reader.provider.ReaderManager.sync(ReaderManager.java:1093)
W/System.err(32501):    at com.noinnion.android.newsplus.reader.provider.ReaderManager.syncEx(ReaderManager.java:1075)
W/System.err(32501):    at com.noinnion.android.newsplus.reader.service.SyncService.doSync(SyncService.java:197)
W/System.err(32501):    at com.noinnion.android.newsplus.reader.service.SyncService.access$000(SyncService.java:57)
W/System.err(32501):    at com.noinnion.android.newsplus.reader.service.SyncService$1.run(SyncService.java:139)
W/System.err(32501):    at com.noinnion.android.newsplus.extension.ExtensionHost$1.run(ExtensionHost.java:186)
W/System.err(32501):    at android.os.Handler.handleCallback(Handler.java:733)
W/System.err(32501):    at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err(32501):    at android.os.Looper.loop(Looper.java:136)
W/System.err(32501):    at android.os.HandlerThread.run(HandlerThread.java:61)
```

To fix it, I have to sign out of the tt-rss plugin, quit News+ via the recent apps, start it again and sign in. Then, it usually works again.

**Comment by jochenberger** [comment]
Still an issue in 2.0.0.

**Comment by moneytoo** [comment]
I experienced this issue on CyanogenMod rom but it worked fine (and still does) on stock rom (Samsung Galaxy S5).

**Comment by jochenberger** [comment]
I'm actually using CyanogenMod. What about you @Kasara?
I still wonder why `TtRssExtension` tries to parse an XML (sub?)string to JSON.

**Comment by noinnion** [comment]
Hi Jochen,

it is possible to have access to your account? I could not reproduce the
issue so it would be good to test it on your account.
If it is ok, send me an email

**Comment by jochenberger** [comment]
Frankly spoken, I'm not a big fan of that idea. What about catching the exception and logging more of the XML string, like the first `max(200, string.length()` chars? Maybe that'll help us to understand what's happening and how an XML string is ending up in the JSON parser in the first place.

**Comment by jochenberger** [comment]
I tried to have a look myself, but when I try to import the tt-rss extension project in eclipse, I get a manifest error:

```
error: Error: No resource found that matches the given name (at 'theme' with value '@style/Theme.Sherlock.Light').
```
